# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fin4teen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  
  pod 'Alamofire', '~> 4.7.0'

  pod 'AlamofireImage', '~> 3.4.0'

#  pod 'Firebase/Analytics'
#
#  pod 'Firebase/Core'
#  pod 'Firebase/Messaging'
end
